version: '3.9'

services:
  todolisttgbot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./logs:/logs
    env_file:
       - .env
    restart: unless-stopped
    network_mode: "host"